#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$SCRIPT_DIR"
echo "--- Desktop2Stereo Installer for Mac (for Apple Silicon Chips: M1, M2, M3, M4...) ---"
echo "- Setting up the virtual environment"

# Set paths
VIRTUAL_ENV="$PROJECT_ROOT/python3"
PYTHON_EXE="python3"

# Check if Python is available
if ! command -v $PYTHON_EXE &> /dev/null
then
    echo "Python is not found in PATH. Please install Python 3.11 first."
    read -p "Press enter to exit..."
    exit 1
fi

# Create virtual environment if it doesn't exist
if [ ! -f "$VIRTUAL_ENV/bin/activate" ]; then
    echo "Creating virtual environment..."
    $PYTHON_EXE -m venv "$VIRTUAL_ENV"
    if [ $? -ne 0 ]; then
        echo "Failed to create virtual environment"
        read -p "Press enter to exit..."
        exit 1
    fi
fi

# Activate virtual environment
echo "- Virtual environment activation"
source "$VIRTUAL_ENV/bin/activate"
if [ $? -ne 0 ]; then
    echo "Failed to activate virtual environment"
    read -p "Press enter to exit..."
    exit 1
fi

# Update pip
echo "- Updating the pip package"
$PYTHON_EXE -m pip install --upgrade pip -r "$SCRIPT_DIR/requirements-pip-options.txt" --no-cache-dir --retries 5 --timeout 120
if [ $? -ne 0 ]; then
    echo "Failed to update pip"
    read -p "Press enter to exit..."
    exit 1
fi

# Install requirements
echo
echo "- Installing the requirements"

$PYTHON_EXE -m pip install -r "$SCRIPT_DIR/requirements-mps.txt" --no-cache-dir --retries 5 --timeout 120
$PYTHON_EXE -m pip install -r "$SCRIPT_DIR/requirements.txt" --no-cache-dir --retries 5 --timeout 120
if [ $? -ne 0 ]; then
    echo "Failed to install requirements"
    read -p "Press enter to exit..."
    exit 1
fi
chmod a+x "$PROJECT_ROOT/../run_mac"
chmod a+x "$SCRIPT_DIR/install-mps"
chmod -R 777 "$PROJECT_ROOT/desktop2steoro/streaming/rtmp"
echo "Python environment deployed successfully."
read -p "You can close this terminal window to exit..."
exit
