"""GUI2-only menu, navigation, and dialog translations."""

from __future__ import annotations


GUI2_MESSAGES = {
    "EN": {
        "menu_settings": "Settings",
        "menu_tools": "Tools",
        "menu_help": "Help",
        "menu_language": "Interface language",
        "menu_theme": "Theme",
        "menu_reset_defaults": "Restore defaults",
        "menu_diagnostics": "Logs and diagnostics",
        "menu_website": "Official website",
        "menu_qq_group": "QQ group",
        "menu_about": "About Desktop2Stereo",
        "language_en": "English",
        "language_cn": "简体中文",
        "theme_system": "System",
        "theme_blue": "Blue",
        "theme_green": "Green",
        "theme_red": "Red",
        "theme_purple": "Purple",
        "theme_orange": "Orange",
        "theme_teal": "Teal",
        "theme_pink": "Pink",
        "theme_grey": "Grey",
        "nav_home": "Home / Run",
        "nav_stereo": "Stereo",
        "nav_quality": "Image settings",
        "nav_performance": "Performance",
        "nav_streaming": "Streaming & XR",
        "nav_advanced": "Advanced",
        "nav_logs": "Logs",
        "nav_help": "Help",
        "home_title": "Home / Run",
        "home_description": "Configure the input source, run mode, and output target, then start or stop real-time processing.",
        "stereo_title": "Stereo parameters",
        "stereo_description": "Tune disparity, depth strength, convergence, and stereo presets to shape the final 3D effect.",
        "quality_title": "Image settings",
        "quality_description": "Adjust color, anti-aliasing, sampling, and sharpness for a clear and stable output image.",
        "performance_title": "Performance",
        "performance_description": "Select compute and capture backends, target FPS, and accelerators to balance throughput and latency.",
        "streaming_title": "Streaming and XR",
        "streaming_description": "Configure headset, network protocol, encoder, audio, and calibration options for remote output.",
        "advanced_title": "Advanced settings",
        "advanced_description": "Configure interface language and theme preferences for the application.",
        "advanced_group_hint": "Expert stereo and acceleration parameters",
        "advanced_shortcut_title": "Advanced parameters moved",
        "advanced_shortcut_body": "Advanced settings are now grouped under Stereo parameters. Use the button below to expand them.",
        "open_advanced_stereo": "Open advanced stereo parameters",
        "interface_settings_title": "Interface settings",
        "interface_settings_body": "Choose the language and theme used by the GUI.",
        "updates_title": "Application updates",
        "updates_body": "Update checking is reserved for the new project update service.",
        "check_updates": "Check for updates",
        "updates_disabled_tooltip": "Temporarily unavailable while the new update connection is being prepared.",
        "update_feature_disabled": "Update checking is temporarily disabled.",
        "logs_title": "Logs and diagnostics",
        "logs_description": "Inspect runtime status, performance records, warnings, and errors for diagnosis and troubleshooting.",
        "home_core": "Core workflow",
        "home_streaming_title": "Streaming and XR parameters",
        "streaming_shortcut_title": "Streaming and XR moved to Home",
        "streaming_shortcut_body": "All Streaming and XR parameters are always visible in a separate section below the Home controls.",
        "open_home_streaming": "Open Home streaming controls",
        "home_tip": "Detailed controls are grouped by task in the navigation rail.",
        "switch_to_legacy_gui": "Legacy Menu",
        "status_idle": "Ready",
        "help_title": "Help",
        "help_description": "Find the official website, QQ community, version details, and project support information.",
        "help_panel_title": "Desktop2Stereo Help and Community",
        "help_panel_body": "Project links, QQ community information, and version details.",
        "help_qr_missing": "QQ QR code has not been provided yet.",
        "help_qq_title": "QQ community",
        "help_website": "Official website",
        "help_group_missing": "Group number has not been provided.",
        "help_copy_group": "Copy group number",
        "help_open_invite": "Open invite link",
        "help_about_title": "About Desktop2Stereo",
        "help_about_body": "Desktop2Stereo is a real-time 2D-to-3D stereo processing tool.",
        "footer_language": "Language",
        "footer_theme": "Theme",
        "qq_title": "QQ group",
        "qq_missing_qr": "QQ QR code has not been provided yet.",
        "qq_missing_number": "Group number has not been provided.",
        "copy_group_number": "Copy group number",
        "open_invite": "Open invite link",
        "close": "Close",
        "about_title": "About Desktop2Stereo",
        "about_body": "Desktop2Stereo is a real-time 2D-to-3D stereo processing tool.",
        "website_open_failed": "Could not open the website: {}",
        "invite_open_failed": "Could not open the invite link: {}",
        "group_number_missing": "The QQ group number is not configured.",
        "group_number_copied": "QQ group number copied.",
        "reset_confirm_title": "Restore defaults?",
        "reset_confirm_body": "All current GUI settings will be replaced by their defaults.",
        "cancel": "Cancel",
        "confirm": "Restore",
        "menu_selected": "Selected",
    },
    "CN": {
        "menu_settings": "设置",
        "menu_tools": "工具",
        "menu_help": "帮助",
        "menu_language": "界面语言",
        "menu_theme": "主题颜色",
        "menu_reset_defaults": "恢复默认设置",
        "menu_diagnostics": "日志与诊断",
        "menu_website": "官方网站",
        "menu_qq_group": "QQ 交流群",
        "menu_about": "关于 Desktop2Stereo",
        "language_en": "English",
        "language_cn": "简体中文",
        "theme_system": "主题",
        "theme_blue": "蓝色",
        "theme_green": "绿色",
        "theme_red": "红色",
        "theme_purple": "紫色",
        "theme_orange": "橙色",
        "theme_teal": "青色",
        "theme_pink": "粉色",
        "theme_grey": "灰色",
        "nav_home": "首页运行",
        "nav_stereo": "立体参数",
        "nav_quality": "画面设置",
        "nav_performance": "性能设置",
        "nav_streaming": "串流与 XR",
        "nav_advanced": "高级设置",
        "nav_logs": "日志诊断",
        "nav_help": "帮助",
        "home_title": "首页运行",
        "home_description": "配置输入来源、运行模式与输出目标，并启动或停止实时处理。",
        "stereo_title": "立体参数",
        "stereo_description": "调整视差、深度强度、收敛与立体预设，控制最终 3D 空间感。",
        "quality_title": "画面设置",
        "quality_description": "调节色彩、抗锯齿、采样与锐度，平衡画面清晰度和稳定性。",
        "performance_title": "性能设置",
        "performance_description": "选择计算与捕获后端、目标帧率和加速器，优化吞吐与延迟。",
        "streaming_title": "串流与 XR",
        "streaming_description": "配置头显、网络协议、编码器、音频与校准参数，用于远程输出。",
        "advanced_title": "高级设置",
        "advanced_description": "配置应用使用的界面语言和主题偏好。",
        "advanced_group_hint": "专家级立体与加速参数",
        "advanced_shortcut_title": "高级参数已归入立体参数",
        "advanced_shortcut_body": "高级设置已统一放入立体参数页面的“显示高级立体参数”区域。",
        "open_advanced_stereo": "打开高级立体参数",
        "interface_settings_title": "界面设置",
        "interface_settings_body": "选择 GUI 使用的界面语言和主题颜色。",
        "updates_title": "应用更新",
        "updates_body": "更新检查已预留给新项目更新服务，当前暂未启用。",
        "check_updates": "检查更新",
        "updates_disabled_tooltip": "新项目更新连接正在准备中，当前暂不可用。",
        "update_feature_disabled": "更新检查功能当前已关闭。",
        "logs_title": "日志与诊断",
        "logs_description": "查看运行状态、性能记录、警告和错误，用于性能分析与故障定位。",
        "home_core": "核心流程",
        "home_streaming_title": "串流与 XR 参数",
        "streaming_shortcut_title": "串流与 XR 已移到首页",
        "streaming_shortcut_body": "全部串流与 XR 参数已常驻显示在首页控件下方的独立区域。",
        "open_home_streaming": "打开首页串流设置",
        "home_tip": "详细控件已按任务分组到左侧导航中。",
        "switch_to_legacy_gui": "旧版菜单",
        "status_idle": "就绪",
        "help_title": "帮助",
        "help_description": "查看官网、QQ 群、版本与项目说明，获取社区支持和最新信息。",
        "help_panel_title": "Desktop2Stereo 帮助与社区",
        "help_panel_body": "项目链接、QQ群信息和版本信息。",
        "help_qr_missing": "暂未提供 QQ 群二维码。",
        "help_qq_title": "QQ 交流群",
        "help_website": "官方网站",
        "help_group_missing": "暂未提供 QQ 群号。",
        "help_copy_group": "复制群号",
        "help_open_invite": "打开邀请链接",
        "help_about_title": "关于 Desktop2Stereo",
        "help_about_body": "Desktop2Stereo 是一个实时 2D 转 3D 立体处理工具。",
        "footer_language": "界面语言",
        "footer_theme": "主题颜色",
        "qq_title": "QQ 交流群",
        "qq_missing_qr": "暂未提供 QQ 群二维码。",
        "qq_missing_number": "暂未提供 QQ 群号。",
        "copy_group_number": "复制群号",
        "open_invite": "打开邀请链接",
        "close": "关闭",
        "about_title": "关于 Desktop2Stereo",
        "about_body": "Desktop2Stereo 是一个实时 2D 转 3D 立体处理工具。",
        "website_open_failed": "无法打开官方网站：{}",
        "invite_open_failed": "无法打开邀请链接：{}",
        "group_number_missing": "尚未配置 QQ 群号。",
        "group_number_copied": "QQ 群号已复制。",
        "reset_confirm_title": "恢复默认设置？",
        "reset_confirm_body": "当前 GUI 设置将全部替换为默认值。",
        "cancel": "取消",
        "confirm": "恢复",
        "menu_selected": "当前",
    },
}


def gui2_text(locale: str, key: str, *args) -> str:
    catalog = GUI2_MESSAGES.get(locale, GUI2_MESSAGES["EN"])
    value = catalog.get(key, GUI2_MESSAGES["EN"].get(key, key))
    return value.format(*args) if args else value
